---
- name: This playbook can be run on nodes WITHOUT python
  hosts: all
  gather_facts: false
  become: false

  tasks:
  - name: Whoami or similar
    raw: whoami
    register: iam
    changed_when: false
  
  - name: uptime
    raw: uptime
    register: up
    changed_when: false

  - name: internet info
    raw: ip a
    register: intranet
    changed_when: false

  - name: outernet info
    raw: curl ifconfig.co
    changed_when: false

  - name: metadata
    raw: curl http://169.254.169.254/latest/meta-data/public-ipv4
    register: publicip
    changed_when: false

  - name: report output
    debug:
      msg:
      - "user: {{iam.stdout}}"
      - "uptime: {{up.stdout}}"
      - "Private IP: {{intranet.stdout_lines[7] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')}}"
      - "Public IP: {{publicip.stdout | ipv4}}"

    